// Sets default values for each position in the highscore and name arrays
global.hiscore[1] = 90000;
global.namescore[1] = "BPF      Stage: 1"; // Me!
global.shipscore[1] = 1;
global.hiscore[2] = 80000;
global.namescore[2] = "KSR      Stage: 1"; // Kaiser
global.shipscore[2] = 2;
global.hiscore[3] = 70000;
global.namescore[3] = "MJC      Stage: 1"; // mjclark
global.shipscore[3] = 3;
global.hiscore[4] = 60000;
global.namescore[4] = "S20      Stage: 1"; // S20-TBL
global.shipscore[4] = 4;
global.hiscore[5] = 50000;
global.namescore[5] = "GZR      Stage: 1"; // Gryzor/Rozyrg
global.shipscore[5] = 5;
global.hiscore[6] = 40000;
global.namescore[6] = "ERA      Stage: 1"; // Alluro
global.shipscore[6] = 4;
global.hiscore[7] = 30000;
global.namescore[7] = "GUS      Stage: 1"; // Gustav
global.shipscore[7] = 3;
global.hiscore[8] = 20000;
global.namescore[8] = "EMS      Stage: 1"; // Emerald Master
global.shipscore[8] = 2;
global.hiscore[9] = 10000;
global.namescore[9] = "UDD      Stage: 1"; // Udderdude
global.shipscore[9] = 1;
global.hiscore[10] = 0;
global.namescore[10] = "<nobody>"; // What the GM registry normally shows when cleared
global.shipscore[10] = 1;
